- name: Install debian packages
  apt:
    name: "{{ debian_packages }}"
    state: present
  register: _apt
  until: _apt is succeeded
  retries: 5
  become: true
- name: Add apt key for MongoDB repository
  apt_key:
    url: "{{ debian.apt_key_url }}"
    state: present
  register: _apt
  until: _apt is succeeded
  retries: 5
  become: true

- name: Add mongo sources list
  become: true
  lineinfile: >
    line="deb http://repo.mongodb.org/apt/ubuntu focal/mongodb-org/4.4 multiverse"
    dest=/etc/apt/sources.list.d/mongodb-org-4.4.list
    state=present
    create=yes  
    #- name: Ensure MongoDB apt repository exists
    #  apt_repository:
    # repo: "{{ debian.apt_repository_repo }}"
    #state: present
    # filename: "mongodb-{{ mongodb_version }}"
    #register: _apt
    # until: _apt is succeeded
    #retries: 5
    #become: true


- name: Install MongoDB Packages (Specific version)
  package:
    name:
      - "mongodb-org={{ mongodb_version }}"
        # - "mongodb-org-server={{ specific_mongodb_version }}"
        # - "mongodb-org-shell={{ specific_mongodb_version }}"
        # - "mongodb-org-mongos={{ specific_mongodb_version }}"
        #  - "mongodb-org-tools={{ specific_mongodb_version }}"
    state: present
  become: true  
    # when:
    # - specific_mongodb_version is defined
    # - ansible_facts.os_family == "Debian"
    # register: _pkg
    # until: _pkg is succeeded
    # retries: 5
